### ISSUE TITLE
Code in docstring does not parse properly

### ISSUE THREAD

**Issue by ariG23498** [ooreilly/mydocstring#13]
# Code
In the following demonstration I have tried parsing a simple docstring.
```python
from mydocstring.parse import GoogleDocString

s = """
Hello

Examples:
    ```python
    a = {
        'a': 1,
        'b': 1,
        'c': 1,
    }
    ```
"""

parser = GoogleDocString(s)
p = parser.parse()

for section in p:
    for k,v in section.items():
        print(f'{k}=>{v}')
```
# Output
```
header=>
text=>
Hello

args=>[]
header=>Examples
text=>\```python
a = {
}
\```

args=>[{'field': '', 'signature': '', 'description': "1,\n    'b': 1,\n    'c': 1,"}]
```

Here as you can see the dictionary in the code is being parsed as arguments. This will break the rendering as well. Do we have a workaround for this? :smile:

**Comment by ooreilly** [comment]
Nice catch! Let me think about what we can do. The first idea that comes to mind is to stop scanning for arguments inside a code block, or perhaps we could disable the args list feature for certain sections?  I also wonder where the `a` went in the description field?

**Comment by ariG23498** [comment]
Yep, the disappearing `a` is something I forgot to mention.
I do not have a clue as to what is happening here.
I think disabling scan in a code block would make sense and would be a really helpful way to overcome this. :thinking:
