### ISSUE TITLE
Copyright statements missing in headers

### ISSUE THREAD

**Issue by gcarleo** [ooreilly/mydocstring#3]
@ooreilly , another "small" thing I noticed: it seems that you don't have copyright/license statements in the headers of your files!

I would like to use your excellent `parser.py` to build the documentation of a project, and would like to copy it in our repo. Would that be ok for you/ would you add your copyright statement before? 

Thanks!

**Comment by gcarleo** [comment]
Great! Thanks for this. I will maybe also try to do a PR here with some of the changes I am doing/planning to do, but I am not sure if they would fit in your original project. 

It would be good to have some feedback from your before that. 
Ideally, it would be nice to have something similar to the `get_method_docstring` found in [here](https://github.com/rahulrrixe/parinx)  and maybe also a related `get_class_docstrings` .  I am assuming these are not already implemented in your project, but it they are I just couldn't find them! 

That's basically what I am planning to add in my extension + some other code to convert your json output to the kind of custom markdown I need for the webpage of the project (this last part is maybe too specialized for your repo though, I guess)

**Comment by ooreilly** [comment]
The extract module can be used to get docstrings (unparsed) both from functions and classes. Take a look at `tests/test_extract.py`. Basically, you want to pass "Class.method" to grab a class method. However, it does not grab all docstrings from a class. 

I also want to point out that once you have extracted a docstring, you can pass it to the `GoogleDocString` object to parse it. You might also want to look at `tests/test_parse.py`. 

Here's an example showing both features:

example.py
```
class Example(object):
    def __init__(self, arg1, arg2):
        """
        This is an example of a docstring that conforms to the Google style guide. 
        The indentation uses four spaces (no tabs). Note that each section starts
        with a header such as `Arguments` or `Returns` and its contents is indented.

        Arguments:

            arg1 (`int`): This description for this argument fits on one line.
            arg2 (`int`, optional): This description is too long to fit on a
                single line. Note that it is continued by being indented. 
        """      
```
Test:
```python
from mydocstring import extract, parse

match = extract.extract("example.py", 'Example.__init__')
google = parse.GoogleDocString(match['docstring'])

google.parse()
print(google.data)  

```
Output:
```
[{'header': '', 'text': '\n\nThis is an example of a docstring that conforms to the Google style guide. \nThe indentation uses four spaces (no tabs). Note that each section starts\nwith a header such as `Arguments` or `Returns` and its contents is indented.\n', 'args': []}, {'header': 'Arguments', 'text': '\n', 'args': [{'field': 'arg1', 'signature': '(`int`)', 'description': 'This description for this argument fits on one line.'}, {'field': 'arg2', 'signature': '(`int`, optional)', 'description': 'This description is too long to fit on a\n    single line. Note that it is continued by being indented. '}]}]
```

I hope it helps! Otherwise I would be happy to clarify and help out. I am interested seeing what you come up with. PR is absolutely welcome!

**Comment by gcarleo** [comment]
@ooreilly , yes good point, however in our case we have a pybind11 c++/based library, so basically we cannot access the .py file directly and we have to use introspection

**Comment by gcarleo** [comment]
basically what's missing here is the equivalent of `extract` but for a loaded class/method: 

```python
import mymodule 

match=extract.extract(mymodule.func1) 
.... 
```

**Comment by ooreilly** [comment]
@gcarleo  I see. It would nice to be able to to extract info from a loaded module. Are you working on this?

An alternative solution would be to add some support for C or C++ so that you can extract from source code:
```
float add(float a, float b)
{
/* This function adds two floating-point numbers together.

Args:
  a : input
  b : input 

Returns:
 The result.
*/
return a + b;
}

```

**Comment by gcarleo** [comment]
Yes, that would be the idea, we have compiled modules and we want to extract docs from them.
I will try to work on this if I find some time... hopefully. Have you already given some thoughts on how you'd to this?

**Comment by ooreilly** [comment]
Yes, you can use the `inspect` module in Python. See here: https://docs.python.org/3/library/inspect.html

If you are interested in the second solution (extract info directly from c, c++ code) let me know and I can see if I can find some time to implement that feature.

**Comment by gcarleo** [comment]
Yes, sorry, I actually already have a first working implementation with inspect, it's not too hard. Your approach for pure c/c++ code would be really great, however in [pybind11 exposed classes](https://pybind11.readthedocs.io/en/stable/advanced/misc.html#generating-documentation-using-sphinx) we cannot do that either (or at least it requires some more thought)

**Comment by ooreilly** [comment]
Alright. Glad to hear that inspect implementation works. I take it there are some shortcomings to this approach that makes you want to explore solution 2 a bit more? 

I haven't worked with pybind11 before so I am not entirely sure what needs to get extracted. My understanding is that you have some c++ source code, and some binding code. Are you sure you want to extract info from the binding code? Why not just from the c++ code itself? Or is your documentation sitting in the bindings?

Is this what you need to extract info from:
```c
PYBIND11_MODULE(example, m) {
    py::options options;
    options.disable_function_signatures();

    m.def("add", [](int a, int b) { return a + b; }, "A function which adds two numbers");
}
```

And we would want to extract the function name `add`, the function args `(int a, int b)`, function body `{ . . }`, and the docstring `"A function .. ."`? I also see that you can pass a reference to the function, or method. That would make things more difficult.

**Comment by gcarleo** [comment]
Correct, basically what happens is that you write the docstring in the bindings, and it is then exposed to python through `__doc__`.  There is a simple pybind11 [example here](https://github.com/pybind/python_example) if you are curious. The `__doc__` method already contains the signature of the function, so luckily enough we don't need to worry about doing that from the c++ side. 
For the example case I linked, you'd do: 

```python
import python_example as pe
print(pe.add.__doc__)
```
and this would give a docstring  
```
add(arg0: int, arg1: int) -> int


        Add two numbers

        Some other explanation about the add function.
```    
Now, the only problem with your parser is that the function signature found in the first line here should be treated/parsed as such, maybe as an additional field in the dict generated by the parser. What do you think? 
This would be really nice to have for our project, in order to automatically generate markdown from the python bindings and more easily handle our [website](https://www.netket.org/) docs. I also suspect that this tool might be very useful for many other projects relying on pybind11. 

See [here](https://github.com/netket/netket/blob/dd75ea25847171f8b4fdfae58271b928422642f6/NetKet/Graph/pygraph.hpp#L176) for an example binding in our code. Notice that we introduced python bindings only recently, and that class I linked to is basically the only one documented at this stage. We are exactly in the process of deciding how to deal with documentation, if on the c++ or python side/both etc... such a pain!
