### ISSUE TITLE
supporting classes

### ISSUE THREAD

**Issue by gunstonej** [ooreilly/mydocstring#7]
hi there, 

I'm really enjoying mydocstring. 

I was wondering if there is any plan to support documenting Classes? 

If not, you demonstrate how to get the classes data in one of the Issues here: [classes example](https://github.com/ooreilly/mydocstring/issues/3#issuecomment-446343736)

i was wondering if there is a similar method that also applies the markdown formatting? 

many thanks

**Comment by gunstonej** [comment]
a little bit more playing demonstrated that you can assess class methods in the same way you access functions:
`mydocstring mydocstring_example.py example_class.__init__ --markdown`

**Comment by ooreilly** [comment]
@gunstonej I'm terribly sorry that I never got back to you. Somehow, I missed this issue. Were you able to access the class data as planned?

**Comment by ooreilly** [comment]
Closed due to inactivity.
