### ISSUE TITLE
class method not parsed if `self` is on a newline after opening bracket

### ISSUE THREAD

**Issue by snazzer** [ooreilly/mydocstring#8]
Consider the class

```
bash-3.2$ cat tst.py
class TestClass:

    def __init__(
            self,
            arg1
    ):
        """
        Args:
            arg1 : an arg
        """
        pass
```

Parsing this fails because `self` is on a newline.

Proposed fix to `PyExtract::extract_method` pattern to change `(self[\w\W]` to `(\s*self[\w\W]`

**Comment by ooreilly** [comment]
Hello @snazzer, thank you for reporting this issue and suggesting a fix. I have implemented the change you suggested. I hope that the problem has been resolved now.

**Comment by snazzer** [comment]
Works! Thanks for the quick response. I had subclassed `PyExtract` to bypass the issue but now I can remove my fix.
